name: CI/CD with Terraform
on:
  push:
    branches:
     - Complete-CI/CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secret.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secret.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secret.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: us-east-2

jobs:
  deploy.infran:
    runs-on: ubunut-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform init
          id: init 
          rum: terraform init -backend-config="bucket=STF_STATE_BUCKET_NAME" -backend-config="region=us-east-2"
          working-directory: ./Terraform
      - name: Terraform Plan
        id: plan
        run: |-
          terraform plan \ 
          -varm"regiom=us-east-2" \
          -varm"public_key=$PUBLIC_SSH_KEY" \
          -varm"private_key=$PRIVATE_SSH_KEY" \ 
          -varm"key_name=deployer-key" \
          -out=PLAN
        working-directory: ./terraform
      - name: Terraform Apply
        id: applu
        run: terraform apply PLAN
        working-directory: ./terraform
    

